export const SyncEvents = {
  PUSH_STARTED: 'SYNC_PUSH_STARTED',
  PUSH_COMPLETED: 'SYNC_PUSH_COMPLETED',
  ITEM_PROCESSED: 'SYNC_ITEM_PROCESSED',
  IDEMPOTENT_SKIP: 'SYNC_IDEMPOTENT_SKIP',
  ITEM_ERROR: 'SYNC_ITEM_ERROR',
  CONFLICT_DETECTED: 'SYNC_CONFLICT_DETECTED',
  CONFLICT_RESOLVED: 'SYNC_CONFLICT_RESOLVED',
  PULL_STARTED: 'SYNC_PULL_STARTED',
  PULL_COMPLETED: 'SYNC_PULL_COMPLETED',
  PULL_EMPTY: 'SYNC_PULL_EMPTY',
  INTERNAL_ERROR: 'SYNC_INTERNAL_ERROR',
  RATE_LIMIT: 'SYNC_RATE_LIMIT',
} as const;

export type SyncEvent = (typeof SyncEvents)[keyof typeof SyncEvents];
