export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PRISMA_UNIQUE_CONSTRAINT: 'PRISMA_UNIQUE_CONSTRAINT',
  PRISMA_RECORD_NOT_FOUND: 'PRISMA_RECORD_NOT_FOUND',
  PRISMA_FOREIGN_KEY_CONSTRAINT: 'PRISMA_FOREIGN_KEY_CONSTRAINT',
  HTTP_ERROR: 'HTTP_ERROR',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_EXTENSION_NOT_ALLOWED: 'FILE_EXTENSION_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_SCOPE_MISMATCH: 'FILE_SCOPE_MISMATCH',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
